<div class="small-header bg-img4">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>Terms of Use</h1>
            </div>
        </div>
    </div>
</div>

<!-- Tabs-->
<section id="terms" class="bg-dark2">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">

                <div>
                    <ul>
                        <!-- 1st -->
                        <li>
                            <h4>INTRODUCTION</h4>
                            <ul>
                                <li> <span>THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF THE INFORMATION TECHNOLOGY ACT, 2000 AND RULES THEREUNDER AS APPLICABLE AND THE PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.</span></li>
                                <li> <span>THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3(1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES GUIDELINES) RULES, 2011 THAT REQUIRES PUBLISHING THE RULES AND REGULATIONS, PRIVACY POLICY AND TERMS OF USE FOR ACCESS OR USAGE OF THIS WEBSITE.</span></li>
                                <li> The domain name www.safegold.com (hereinafter referred to as the
                                    <span>The domain name www.Suvarnasiddhi.com (hereinafter referred to as the “Website”) is owned by Suvarnasakalp Private Limited, a company incorporated under the Companies Act, 2013, ("Suvarnasiddhi").The objective of the Website is to facilitate buying safe keeping/vaulting and delivery/fulfilment of gold and providing related services thereto that may be offered by Suvarnasiddhi to Customers on or through the Platform (“Services”).</span>.
                                </li>
                                <li>Suvarnasiddhi does not guarantee any returns, on any transactions consummated vis-à-vis the Platform, to any person, either directly or indirectly. The Customer (hereinafter referred to as “You”, with the term “Your” being construed accordingly) shall be solely responsible for undertaking appropriate and effective due diligence and related analysis before undertaking any transactions pursuant to these Terms of Use. Suvarnasiddhi may publish research and opinions on this Website or on other parts of the Platform, for general information purposes. You may not rely on any such information for forming Your purchase or other decisions consummated on the Platform. You further acknowledge and agree that Suvarnasiddhi and its officers, directors, employees, agents and affiliates will have no liability for Your purchase or other decisions using the Website and/or any other part of the Platform.
                                </li>
                                <li> The term “Customer” shall mean an individual, who is willing to avail Suvarnasiddhi’s Services using the Platform and is registered as a ‘customer’ on the Platform.
                                </li>
                                <li> For the purpose of these Terms of Use <span>(“Terms”)</span>, wherever the context
                                    so requires, the term:
                                    <ul>
                                        <li>“Customer Account”shall mean the account created whether by You or otherwise, in accordance with these Terms.
                                        </li>
                                        <li>“Customer Account Information” shall mean the information provided by You for the purpose of creation of the Customer Account.
                                        </li>
                                        <li>“Customer Request” shall mean a Delivery Request, Sale Request or Exchange Request placed by You in relation to the Customer Gold.
                                        </li>
                                        <li>“Distributor” shall mean any Person resident in India, in accordance with applicable laws, who is willing to act as an intermediary for the provision of Services by Suvarnasiddhi.
                                        </li>
                                        <li>“Force Major Event”shall mean any event that is beyond the reasonable control of Suvarnasiddhi and shall include, without limitation, sabotage, fire, flood, explosion, act of God, civil commotion, strikes, lockouts or industrial action of any kind, riots, insurrection, war, acts of government, computer hacking, civil disturbances, unauthorised access to computer data and storage device, computer crashes, virus attacks, breach of security and encryption, and any other similar events not within the control of Suvarnasiddhi and which Suvarnasiddhi is not able to overcome.
                                        </li>
                                        <li><span>“Person”</span> shall mean an individual, a corporation, a
                                            partnership, a joint
                                            venture, a trust, an unincorporated organization and any other legal entity.
                                        </li>
                                        <li>“Platform”means collectively: (i) the Website (ii) any internet website(s) operated by Distributors through which any Customer may purchase any gold from Suvarnasiddhi; and (iii) any mobile based software applications/programs offered by any Distributor through which a Customer may purchase gold from Suvarnasiddhi.
                                        </li>
                                    </ul>
                                </li>
                                <li>In addition to the terms defined in Clause 1.6, additional terms used herein shall have the respective meanings assigned thereto in the Terms contained hereinafter.
                                </li>
                            </ul>
                        </li>
                        <!-- 2nd -->
                        <li>
                            <h4>ACCEPTANCE OF TERMS</h4>
                            <ul>
                                <li> Suvarnasiddhi reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms at any time by posting update notification on the Website or on other parts of the Platform and communicating the notification to You in accordance with these Terms. It is Your sole responsibility to review these Terms based on such update notifications. Your continued use of the Website or any Services following the posting of changes shall be deemed to mean that You accept and agree to the revisions. As long as You comply with these Terms, Suvarnasiddhi grants You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.
                                </li>
                                <li>Accessing, browsing or otherwise using the Website indicates Your agreement to all the terms and conditions under these Terms. You are advised to read these Terms carefully before proceeding. By impliedly or expressly accepting these Terms, You also accept and agree to be bound by all Suvarnasiddhi’s policies, including but not limited to its privacy policy (“Privacy Policy”), as amended from time to time.
                                </li>
                                <li>You may not use the Website or avail of the Services using any part of the Platform if You do not accept the Terms or are unable to be bound by the Terms. As a condition of Your access to and use of the Website or the provision of any Services to You using the Platform, You agree that You will comply with all applicable laws and regulations when using the Platform. If Suvarnasiddhi is of the opinion that the Customer Account is being used by You for any unlawful purpose, Suvarnasiddhi shall have the right to take all action available to it, including black-listing or blocking You from using the Services on its Website or blocking Your access to the Services through the Platform or intimating the relevant authorities of such unlawful activities.
                                </li>
                            </ul>
                        </li>
                        <!-- 3rd -->
                        <li>
                            <h4>MEMBER ELIGIBILITY</h4>
                            <ul>
                                <li> Use of the Website and/or the Services is available only to Persons who can enter into legally binding contracts under the Indian Contract Act, 1872 and to Persons resident in India. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents and persons of unsound mind are not eligible to use the Website or the Services. Any person under the age of 18 shall not register on the Website and shall not transact on or use the Platform in relation to or for any Services. Suvarnasiddhi reserves the right to terminate any Person’s membership and/or refuse to provide such Person with access 3 to the Website and/or any Services if it is brought to Suvarnasiddhi’s notice or if it is discovered that such Person is not eligible to use the Website and/or any Service.
                                </li>
                            </ul>
                        </li>
                        <!-- 4th -->
                        <li>
                            <h4>CUSTOMER’S ACCOUNT AND REGISTRATION OBLIGATIONS</h4>
                            <ul>
                                <li> The Website allows very limited and restricted access to the Services for unregistered users.
                                </li>
                                <li> You shall have an option to either place an order for gold directly on the Website or with a Distributor through the Platform.
                                </li>
                                <li> Creation of Customer Account on the Platform
                                    <ul>
                                        <li> For placing an order for any Services, You will have to create the Customer Account on the Platform prior to placing such an order, which can be done either directly by sending a request on the Platform or through an invitation sent by Suvarnasiddhi. As part of the registration process, You will be required to provide certain Customer Account Information and details, including Your mobile number, an e-mail id, password and any other information deemed necessary by Suvarnasiddhi.
                                        </li>
                                        <li> While registering with the Website to avail the Services, You shall not:
                                            <ul>
                                                <li>create any Customer Account for anyone other than Yourself, unless such person's prior permission has been obtained;
                                                </li>
                                                <li> use a Customer Account that is in the name of another person with the intent to impersonate that person; and
                                                </li>
                                                <li>use a name for the Customer Account that is otherwise offensive, vulgar or obscene or unlawful.
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li> Creation of Customer Account by the Distributor
                                    <ul>
                                        <li> For placing an order through the Distributor in accordance with these Terms, You authorize the Distributor to create an account using the Platform, on Your behalf, prior to placing such an order. As part of the registration process, You will be required to provide certain Customer Account Information and details, including Your mobile number, an e-mail id, password and any other information deemed necessary by Suvarnasiddhi and/or Distributor (as the case may be).
                                        </li>
                                        <li> For the purpose of this Clause 4.4, You agree to ratify such authorization retrospectively. You further agree and authorise the Distributor to share any and all of Your information with Suvarnasiddhi as and when requested by Suvarnasiddhi without requiring any further authorisations from You.
                                        </li>
                                        <li> You hereby agree and understand that these Terms shall be applicable to
                                            You irrespective of whether the Customer Account is created directly by You
                                            or by the Distributor, for and on Your behalf. Further, these Terms shall
                                            apply
                                            mutatis mutandis for any orders placed by You, whether for purchase or
                                            delivery/fulfilment of gold, with the Distributors.
                                        </li>
                                        <li> You hereby agree and understand that these Terms shall be applicable to You irrespective of whether the Customer Account is created directly by You or by the Distributor, for and on Your behalf. Further, these Terms shall apply mutatis mutandis for any orders placed by You, whether for purchase or delivery/fulfilment of gold, with the Distributors.
                                        </li>
                                    </ul>
                                </li>
                                <li> You hereby acknowledge that You will be fully responsible for all activities that occur under the Customer Account.
                                </li>
                                <li> Customer’s Obligations
                                    <ul>
                                        <li>You will be responsible for maintaining the confidentiality of the Customer Account Information, and shall be fully responsible for all activities that occur under the Customer Account. You agree to, (i) immediately notify Suvarnasiddhi of any unauthorised use of the Customer Account Information or any other breach of security; and (ii) exit from the Customer Account at the end of each session. Suvarnasiddhi cannot and will not be liable for any loss or damage arising from Your failure to comply with this Clause. You may be held liable for losses incurred by Suvarnasiddhi or any user or visitor of the Platform due to authorised or unauthorised use of the Customer Account, as a result of your failure in keeping the Customer Account Information confidential.
                                        </li>
                                        <li> You shall ensure that the Customer Account Information provided by You in the Platform’s registration form is complete, accurate and up-to-date. Use of another Customer’s account information for availing of any of the Services and/or for use of the Platform is expressly prohibited.
                                        </li>
                                        <li> You agree that if You provide any information that is untrue, inaccurate, not current or incomplete, (or becomes untrue, inaccurate, not current or incomplete) or if Suvarnasiddhi has reasonable grounds to suspect that such information is untrue, inaccurate, not current, incomplete, or not in accordance with these Terms, Suvarnasiddhi shall have the right to indefinitely suspend or terminate or block access to the Customer Account on the Platform and refuse to provide You with access to the Platform.
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <!-- 5th -->
                        <li>
                            <h4>USE OF THE WEBSITE AND SERVICES</h4>
                            <ul>
                                <li> You agree, undertake and covenant that, during the use of the Website or any other
                                    part of the Platform, You shall not host, display, upload, transmit or share any
                                    information that:
                                    <ul>
                                        <li> belongs to another person or entity and to which You do not have any
                                            right;
                                        </li>
                                        <li>s grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another person's privacy, hateful or racially or ethnically objectionable, or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever;
                                        </li>
                                        <li> is misleading in any way;</li>
                                        <li> involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";
                                        </li>
                                        <li> infringes upon or violates any third party's rights including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, e-mail address, physical address or phone number) or rights of publicity;
                                        </li>
                                        <li> tries to gain unauthorized access or exceeds the scope of authorized access to the Website or any other part of the Platform or to profiles, blogs, communities, account information, bulletins, or other areas of the Website or other parts of the Platform or solicits passwords or personally identifying 5 information for commercial or unlawful purposes from other users of the Website or any other part of the Platform;
                                        </li>
                                        <li> interferes with another user’s use of the Website or any other part of the Platform;
                                        </li>
                                        <li>refers to any website or URL that, in Suvarnasiddhi’s sole discretion, contains material that is inappropriate for the Website or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms;
                                        </li>
                                        <li> deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
                                        </li>
                                        <li> contains software viruses or any other computer codes, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms or other computer programming routines that may damage, detrimentally interfere with, diminish value of, covertly intercept or steal any system, data or personal information; or
                                        </li>
                                        <li> violates any law for the time being in force.</li>
                                    </ul>
                                </li>
                                <li> You must comply with the provisions contained in these Terms and the Privacy Policy. Suvarnasiddhi may review Your conduct for compliance purposes, but shall have no obligation to do so.
                                </li>
                                <li> You acknowledge that the Services are for Your personal use and agree not to publish the gold prices or descriptions of gold and/or any other information displayed on the Platform (in lieu of Your access to the Platform) on any other medium. You shall not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software, products or services obtained from the Services.
                                </li>
                                <li> Subject to these Terms and the Privacy Policy, You hereby grant to Suvarnasiddhi a nonexclusive, worldwide, royalty-free right to (a) collect, store and transmit Your data, in each case solely to the extent necessary to provide the Services to You, and (b) share Your data or interact with other people, to distribute and publicly perform and display Your data as You direct or enable through the Services.
                                </li>
                                <li>You represent and warrant that: (i) You have obtained all necessary rights, releases and permissions to provide all Your data to Suvarnasiddhi and to grant the rights granted to Suvarnasiddhi in these Terms and (ii) Your data and its transfer to and use by Suvarnasiddhi as authorized by You under these Terms do not violate any laws or rights of any third party, including without limitation any intellectual property rights, rights of privacy, or rights of publicity, and any use, collection and disclosure authorized herein is not inconsistent with the terms of any applicable privacy policies. Other than its security obligations under these Terms and the Privacy Policy, Suvarnasiddhi assumes no responsibility or liability for Your data, and You shall be solely responsible for Your data and the consequences of using, disclosing, storing, or transmitting it.
                                </li>
                                <li> Suvarnasiddhi shall not be held liable for any loss of data, technical or otherwise, information, or for particulars supplied by You, due the reasons beyond its control like corruption of data or delay or failure to perform as a result of a Force Major Event.
                                </li>
                                <li>Suvarnasiddhi shall have the sole discretion to determine the locations and pin codes it may want to serve.
                                </li>
                                <li>The provision of Services may be interrupted, including for maintenance, repairs, upgrades, or network or equipment failures. Suvarnasiddhi strives to keep the Services up and running; however, all online services suffer occasional disruptions and outages, and Suvarnasiddhi isn’t liable for any disruption or loss You may suffer as a result.
                                </li>
                                <li> Suvarnasiddhi may discontinue some or all of the Services, including certain features and the support for certain devices and platforms, at any time.
                                </li>
                            </ul>
                        </li>
                        <!-- 6th -->
                        <li>
                            <h4>TERMS AND CONDITIONS OF SERVICE </h4>
                            <ul>
                                <li> The Services by Suvarnasiddhi shall be provided for a term commencing from the date of creation of the Customer Account.
                                </li>
                                <li> Placing an Order and Verification
                                    <ul>
                                        <li> Prior to placing an order, You may be required to provide certain know Your customer (KYC) documentation and other information as may be required by Suvarnasiddhi and in such form and manner as it may deem fit.
                                        </li>
                                        <li> Once such documentation and other information is provided by You to Suvarnasiddhi or the Distributor (as the case may be), You shall be entitled to place an order (or authorize the Distributor to place an order on Your behalf) on the Platform (“Customer Order”).
                                        </li>
                                        <li> You agree that Your continued use of the Platform, consequent upon the creation of the Customer Account, is subject to verification by Suvarnasiddhi and/or the Distributors (as the case may be), of the information and documentation provided by You. You hereby grant Suvarnasiddhi and/or the Distributors (as the case may be) permission to conduct such verification, in such form and manner as it may deem fit.
                                        </li>
                                        <li>You further acknowledge that Suvarnasiddhi reserves the right for such verification either on registration of the Customer Account or at any time thereafter.
                                        </li>
                                    </ul>
                                </li>
                                <li> Purchase of Gold
                                    <ul>
                                        <li>This Website as well as the other parts of the Platform offer Services for Customers who wish to purchase gold for personal consumption in accordance these Terms.
                                        </li>
                                        <li>You shall be entitled to purchase gold either directly on the Website or through a Distributor using the Platform.
                                        </li>
                                        <li> In both cases, You can buy gold at the market linked prices of gold shown on the Platform. However, in case of gold being purchased from a Distributor, You would be intimated of the prices through the Distributor. Market linked prices means that these quotes are linked to the prices of gold in the commercial bullion market in India.
                                        </li>
                                        <li> It is hereby clarified that such market linked prices of gold shall constitute fully binding offers and would be an invitation to offer to purchase gold at the said market prices to all Customer Account holders. Notwithstanding the foregoing, You understand that these prices may vary multiple times within a day, and accordingly Your payment obligations for any order placed on the Website will depend on the market linked prices than prevailing.
                                        </li>
                                        <li> Simultaneous with the placing of the Customer Order, You will be required to make payments through a payment gateway or in such other manner as may be prescribed by Suvarnasiddhi or the Distributor in this regard to a no-lien bank account set up by Suvarnasiddhi for the purpose of receiving purchase consideration from Customers (and for no other purpose) (such account being the Collection Account’). It is hereby clarified that once a Customer Order is placed, You are not entitled to cancel a Customer Order, provided however that Customer Order shall stand cancelled if the payment fails for any reason whatsoever in accordance with this Clause 6.3. Upon placing the Customer Order, Suvarnasiddhi may issue a provisional invoice to You in accordance with these Terms pending realization of money.
                                        </li>
                                        <li> .Within a period of 1 (One) business day of the Customer Order being placed or such further period as may be required by Suvarnasiddhi, pending receipt of money by Suvarnasiddhi in the Collection Account, You shall be intimated of the Customer Order placed and Your gold account on Your dashboard shall be updated to reflect confirmed gold balance (“Customer Gold Account”). While the balance will reflect in Your dashboard, it will be confirmed only after realization of the payment from You.
                                        </li>
                                        <li> If, however, the payments are not received within a period of 2 (Two) business days of placing the Customer Order, You shall be intimated of the same in accordance with these Terms, and the Customer Order shall stand cancelled, and the Customer Gold Account shall accordingly stand amended.
                                        </li>
                                        <li> Suvarnasiddhi reserves the right to cancel a Customer Order, at its sole discretion, if Your information, provided prior to placing the Customer Order, is not found acceptable and Suvarnasiddhi is of the opinion that You are not eligible to purchase gold. The Customer Gold Account shall accordingly stand amended. Notwithstanding the foregoing, Suvarnasiddhi also has the right to freeze the Customer Account until it receives KYC and other documentation in a form and manner satisfactory to Suvarnasiddhi.
                                        </li>
                                        <li>Once the payments are received by Suvarnasiddhi and the KYC information is found acceptable, Suvarnasiddhi shall issue an invoice to You confirming the Customer Order placed within a period of 3 (Three) business days of placing such order, in a manner it may deem fit.
                                        </li>
                                        <li> Notwithstanding anything to the contrary contained in these Terms, Suvarnasiddhi shall be entitled to accept or reject a Customer, for any reason whatsoever, at its sole discretion.
                                        </li>
                                        <li> . In case of rejection of a Customer Order in accordance with these Terms, where payments have been received by Suvarnasiddhi, such payments shall be returned to You to the bank account indicated by You or in such other manner (depending on how the payment was made by You), subject to the terms and conditions indicated in the Section titled ‘Pricing & Fee’.
                                        </li>
                                    </ul>
                                </li>
                                <li> Appointment of Intermediaries
                                    <ul>
                                        <li> Suvarnasiddhi or the Security Trustee (as the case may be) may from time to time appoint intermediaries who shall assist Suvarnasiddhi in providing the Services to You (“Intermediaries”). The term, “Intermediaries” shall mean the Security Trustee, Vault Keeper and shall include any and all Persons appointed by Suvarnasiddhi or the Security Trustee (as the case may be) upon placement of a Customer Order (and successful payment of monies in lieu thereof) till the 8 consummation of the Customer Requests placed by You in accordance with these Terms. You hereby consent to the appointment of such Intermediaries, for and on Your behalf, by Suvarnasiddhi or the Security Trustee (as the case may be).
                                        </li>
                                        <li>You acknowledge and understand that these Intermediaries have been appointed to ensure that Your Customer Orders/Customer Requests are duly complied with in accordance with these Terms. You additionally acknowledge that certain payments will have to be made to these Intermediaries for their appointment and services in relation thereto, which shall be borne by Suvarnasiddhi on Your behalf unless otherwise indicated in these Terms.
                                        </li>
                                    </ul>
                                </li>
                                <li> Appointment of Security Trustee
                                    <ul>
                                        <li>You hereby acknowledge and agree that in order to ensure that Your Customer Orders/Customer Requests are fulfilled in all circumstances, a first and exclusive charge on the Customer Gold by way of hypothecation will be created in favour of IDBI Trusteeship Services Limited or any successor Person (“Security Trustee”).
                                        </li>
                                        <li> By accepting these Terms, You further agree to accede to the terms for such arrangement with the Security Trustee (i.e., a security trustee agreement) and for creation of the charge over the Customer Gold by way of a deed of hypothecation or the like (collectively, “Security Trustee Agreements”). By clicking on “I Accept”, You acknowledge that You will accede to the Security Trustee Agreements (upon such date) as if You had been named as an original party to the same and had executed each of such Security Trustee Agreements; and will be bound by all the terms and conditions of the Security Trustee Agreements.
                                        </li>
                                        <li> In the event of any expenses or charges remaining payable to any Intermediaries or otherwise till actual delivery or fulfilment of any of Your Customer Orders/Customer Requests for any reason, including where Suvarnasiddhi is unable to pay these expenses or charges for any reason whatsoever, thereby adversely effecting or jeopardizing the fulfilment of Your Customer Orders/Customer Requests, then the Security Trustee will be entitled to sell part of the Customer Gold and satisfy such outstanding expenses or charges as required in accordance with these Terms read with the Security Trustee Agreements. The sums due to You and/or gold (as the case may be) to be delivered after settling the aforementioned charges, would be dealt with in accordance with Clause 13 of these Terms read with the Security Trustee Agreements.
                                        </li>
                                        <li>By way of these Terms, You authorize the Security Trustee to act on Your behalf to ensure that Your interests are adequately protected.
                                        </li>
                                    </ul>
                                </li>
                                <li> Safe Keeping/Vaulting of Gold
                                    <ul>
                                        <li>Gold purchased by You corresponding to the Customer Order shall be stored with a custodian in a vault on Your behalf (“Vault Keeper”).
                                        </li>
                                        <li> You hereby authorize (i) appointment of such Vault Keeper to safe keep the gold purchased; and (ii) Suvarnasiddhi to store such gold products purchased by You, including, but not limited to, bullion, coins or jewellery (as the case may be) in the secured vault on Your behalf (“Customer Gold”). It is hereby clarified that Your purchase of the gold corresponding to the Customer Order 9 shall be deemed to be completed and title in relation thereto shall be deemed to have been passed upon such relevant portion of the Customer Gold being stored in the vault with the Vault Keeper on Your behalf or upon a final invoice being issued by Suvarnasiddhi in accordance with these Terms, subject to applicable laws.
                                        </li>
                                        <li> . To ensure that the Customer Gold stored in such vault is adequately protected, necessary insurance policy/ies has been obtained by the Vault Keeper, where the cost of insurance to safe keep the same will be borne by the Vault Keeper. Pursuant to such insurance policy/ies, for any loss or damage to the Customer Gold stored in the vault, You further authorize the Security Trustee to act as Your beneficiary under the insurance policy/ies and to take all steps necessary to protect Your interests.
                                        </li>
                                        <li>While the Vault Keeper has taken the necessary insurance policy/ies, in case of occurrence of an event not covered in such insurance policy/ies, the Customer Gold may be at risk. The broad areas covered by such insurance policy/ies as well as the primary exclusions would be detailed on the Website. It would be Your responsibility to view the Website to check the inclusions and exclusions under such insurance policy/ies.
                                        </li>
                                    </ul>
                                </li>
                                <li> Delivery of Gold
                                    <ul>
                                        <li>This Website and other parts of the Platform offer Services for Customers who wish to procure delivery of the Customer Gold in accordance with these Terms.
                                        </li>
                                        <li>You shall be entitled to procure delivery of the Customer Gold, either directly on the Website or through a Distributor using the Platform (being authorized by You to do so on Your behalf) (“Delivery Request”).
                                        </li>
                                        <li> Upon placing the Delivery Request, You shall be required to pay for the applicable delivery charges and confirm the Delivery Request, in a form and manner acceptable to Suvarnasiddhi. Your Customer Gold Account shall be provisionally debited corresponding to the quantity of the Customer Gold sought to be delivered (“Delivered Customer Gold”).
                                        </li>
                                        <li> Within a period of 7 (Seven) business days of the Delivery Request being confirmed or such further period as may be required by Suvarnasiddhi, Suvarnasiddhi shall arrange for delivery of the Delivered Customer Gold at the shipping address indicated by You. You shall be solely responsible for ensuring that the correct address is furnished by You on the Platform for processing such Delivery Request. You shall not be entitled to change the shipping address after the Delivery Request is processed by Suvarnasiddhi. Notwithstanding the foregoing, You shall have the option to change the shipping address, before the Delivered Customer Gold is actually shipped. In the event You wish to change the shipping address, You have to log-in to Your Customer Account on the Platform and make such request in a form and manner indicated by Suvarnasiddhi and shall provide supporting documentation/information for the new address, as may be required by Suvarnasiddhi.
                                        </li>
                                        <li> You should carefully examine the package delivered and shall not accept deliveries where the packaging has been tampered with. If, however, You are of the view that the package delivered has been tampered with, You shall be required to intimate Suvarnasiddhi immediately of the same, and provide such other information as may be required by Suvarnasiddhi in this regard (“Return Request”). Within a period of 10 (Ten) business days of Return Request being placed (with the original package of Delivered Customer Gold being delivered to Suvarnasiddhi, in a manner indicated by Suvarnasiddhi), and the same being approved by Suvarnasiddhi, Suvarnasiddhi shall arrange for re-delivery of the Delivered Customer Gold at the shipping address indicated by You. The costs for such shipping shall be borne by Suvarnasiddhi alone, and not by You. However, in the event of frivolous and unjustified Return Requests made by You, Suvarnasiddhi reserves the right to take all action available to it, including black-listing or blocking You from using the Services on its Website or on any other part of the Platform.
                                        </li>
                                        <li> You, upon signing the delivery receipt, acknowledge the receipt of the Delivered Customer Gold in terms of the Delivery Request placed with Suvarnasiddhi. Suvarnasiddhi shall not be liable to You for any refund/replacement, under any circumstance, for any subsequent complaints with respect to such deliveries and/or any failure on your part (as the case may be) to comply with these Terms.
                                        </li>
                                        <li> Upon receipt of the delivery confirmation by Suvarnasiddhi, the Customer Gold Account shall be finalized by debiting the Delivered Customer Gold from the Customer Gold Account.
                                        </li>
                                        <li>It shall be Your responsibility to ensure that You are available to receive the Delivered Customer Gold at the time of delivery. If You are not available at the time of delivery, Suvarnasiddhi/ courier agent may try and deliver the item again before returning the same to Suvarnasiddhi. In case of return of the Delivered Customer Gold to Suvarnasiddhi, Customer Gold Account shall be credited for the Delivered Customer Gold, provided however that Suvarnasiddhi is of the opinion that the packaging has not been tamped with. It is hereby clarified that should a request for re-delivery be made by You, You shall be solely liable to incur the applicable delivery charges for delivering the Delivered Customer Gold.
                                        </li>
                                        <li> In case of Suvarnasiddhi’s inability to make deliveries of Delivered Customer Gold due to a Force Majeure Event, Suvarnasiddhi shall intimate You of the same and may require that the deliveries be effectuated through specific modes. In such a case, You hereby agree to bear any additional costs and fees necessary for the delivery to be complete.
                                        </li>
                                        <li> Suvarnasiddhi will not be able to deliver a fractional quantity of gold below such threshold as Suvarnasiddhi shall notify for this purpose even if a Customer Request is made for such fractional quantity (“Threshold Quantity”). You are advised to check the Website periodically to determine the Threshold Quantity as the same may be revised from time to time. In the event that any Customer Gold below the Threshold Quantity is to be delivered to you, then please note that such Customer Gold shall instead be sold by Suvarnasiddhi based on the sale prices displayed on the Platform and You will instead receive the applicable sale proceeds in Your bank account, details of which are provided by You. If there is any mistake in the account number provided by You, Suvarnasiddhi would not be held responsible for the same.
                                        </li>
                                        <li>You are required to take delivery of Your Customer Gold within such maximum period as shall be specified for this purpose by Suvarnasiddhi from time to time in the Pricing and Fees section of the Platform (“Maximum Storage Period”). For the purposes of making delivery to You, You are required to provide a valid address and/or any other documents/information that may be specified in this regard by Suvarnasiddhi on the Platform from time to time. You may provide such address to Suvarnasiddhi at any time during the Maximum 11 Storage Period. In the event that no valid address has been provided by You during the Maximum Storage Period, then Suvarnasiddhi shall for a period 1 year commencing from the date of expiry of Maximum Storage Period (such period being the “Grace Period”) attempt at least once to contact You using the contact information provided by You to Suvarnasiddhi to obtain either (i) an address to which You would require the gold in question to be delivered or (ii) Your bank account details into which sale proceeds of the Customer Gold shall be deposited. In the event that Suvarnasiddhi has not been able to contact You during the applicable Grace Period using the contact information provided by You or where You shall during the Grace Period either fail to:
                                            <ul>
                                                <li> take delivery of the gold in question for any reason whosoever (including where You shall not have provided any address to take delivery of such gold); or
                                                </li>
                                                <li> provide the details for a valid bank account into which the
                                                    proceeds of
                                                    any sale of such Customer Gold is to be deposited;
                                                </li>
                                            </ul>
                                           then upon expiry of the applicable Grace Period for the Customer Gold in question, Suvarnasiddhi shall purchase such Customer Gold with the purchase price being the applicable prevailing price notified by Suvarnasiddhi on the Platform for purchase of gold from Customers. The purchase proceeds realized from such sale (“Final Sale Proceeds”) after deducting any amounts payable to Suvarnasiddhi as storage charges for storage of such gold after the Free Storage Period, shall be deposited into a no-lien bank account operated by the Security Trustee who shall be the sole signatory to such bank account. In the event that You shall during a period of a period of 3 years commencing from the date of expiry of the applicable Grace Period (such period being the “Final Claim Period” ) notify either Suvarnasiddhi or the Security Trustee that You are claiming the applicable Final Sale Proceeds, the Security Trustee shall issue suitable instructions to transfer the Final Sale Proceeds to such bank account as You shall notify for this purpose. Please note that to claim the Final Sale Proceeds You will be required to provide details of a valid bank account and that the Final Sale Proceeds will not be transferred in the absence of such details. At no time will the Final Sale Proceeds be paid to you in cash. In the event that You shall not claim its Final Sale Proceeds within the Final Claim Period, then the Final Sale Proceeds shall be transferred to the Prime Minister’s Relief Fund or such other fund as You may designate for this purpose at any time prior to the expiry of the Grace Period.
                                        </li>
                                    </ul>
                                </li>
                                <li> Sell the Customer Gold
                                    <ul>
                                        <li> You may be provided an option to sell the Customer Gold during market hours based on the sale prices on the Platform, either directly on the Website or through a Distributor using the Platform (being authorized by You to do so on Your behalf). If the prices are found acceptable to You, You shall confirm the sale request, in a form and manner acceptable to Suvarnasiddhi (“Sale Request”). Your Customer Gold Account shall be debited corresponding to the quantity of the Customer Gold sought to be sold vide the Sale Request (“Sold Customer Gold”).
                                        </li>
                                        <li> Within a period of 5 (Five) business days of the Sale Request being confirmed or such further period as may be required by Suvarnasiddhi, the payment, pursuant to the Sale Request, shall be disbursed by Suvarnasiddhi at the sale prices indicated at the time of placing such Sale Request. Suvarnasiddhi shall arrange for such payments to be made to Your bank account, details of which are provided by You. If there is any mistake in the account number provided by You, Suvarnasiddhi would not be held responsible for the same.
                                        </li>
                                        <li> It is hereby clarified that Suvarnasiddhi will provide this service on a best efforts basis and only when the commercial bullion market is in operation. Suvarnasiddhi does not in any way guarantee that this option will be available to You at all times. Further, the buyer of the Sold Customer Gold may be either Suvarnasiddhi or another party (being interested in buying the Sold Customer Gold). Suvarnasiddhi shall not be held liable for any actions of such third-party purchaser.
                                        </li>
                                        <li> You will be provided with free storage for your Customer Gold for such period as more particularly stipulated by Suvarnasiddhi in this regard from time to time at its sole discretion and notified to Customers in the Pricing and Fees section of the Platform (“Free Storage Period”). After the expiry of the Free Storage Period, Suvarnasiddhi shall be entitled to levy storage charges for such Customer Gold at such rate as Suvarnasiddhi shall have specified at its sole discretion in the Pricing and Fees section of the Platform from time to time. You are advised to periodically check the Pricing and Fees section of the Platform to understand these storage charges and the time within which You would be required to make payment of such storage charges. In the event that You fail to make payment of any storage charges within the time stipulated in this regard, Suvarnasiddhi shall be entitled to sell such portion of Your Customer stored with the Vault Keeper that is necessary or required to recover the unpaid storage charges in question.
                                        </li>
                                        <li> While reasonable efforts will be made to offer You a competitive price for the Customer Gold, there is no guarantee that the price offered to You will be close to or comparable with other prices available in the market.
                                        </li>
                                    </ul>
                                </li>
                                <li> Exchange for jewellery
                                    <ul>
                                        <li> You may be provided an option to choose one of the standard pieces which are available against the Customer Gold sought to be exchanged for jewellery or gift vouchers with a jeweller selected by Suvarnasiddhi, either directly on the Website or through a Distributor (being authorized by You to do so on Your behalf) (“Empanelled Jeweller”), details of which shall be intimated by Suvarnasiddhi to You. If any specified jewellery pieces or gift vouchers are found acceptable to You, You shall place the request and indicate the relevant jewellery piece or gift voucher, in a form and manner acceptable to Suvarnasiddhi (“Exchange Request”). Your Customer Gold Account shall be provisionally debited corresponding to the quantity of the Customer Gold sought to be exchanged vide the Exchange Request (“Exchanged Customer Gold”). It is hereby clarified that any costs request to be paid by You pursuant to the Exchange Request shall be as per the terms indicated by the Empanelled Jeweller to You.
                                        </li>
                                        <li> Within a period of 3 (Three) business days of the Exchange Request being confirmed or such further period as may be required by Suvarnasiddhi, Suvarnasiddhi shall intimate the Empanelled Jeweller of such Exchange Request who shall arrange for delivery of the specified jewellery piece or gift voucher to the relevant shipping address indicated by You, pursuant to the Exchange Request. You shall be solely responsible for ensuring that the correct address is furnished by You on the Website or through the Platform for processing such Exchange Request. You shall not be entitled to change the shipping address after the Exchange Request is processed by Suvarnasiddhi. Notwithstanding the foregoing, You shall have the option to change the shipping address, before the jewellery piece or gift voucher is actually shipped by the Empanelled Jeweller. In the event You wish to change the shipping address, You have to log-in to Your Customer Account on the Website or otherwise access Your Customer Account through the Platform and make such request in a form and manner indicated by Suvarnasiddhi and shall provide supporting documentation/information for the new address, as may be required by Suvarnasiddhi.
                                        </li>
                                        <li> You understand and agree that once You have placed an Exchange Request for exchanging Customer Gold with jewellery piece or gift voucher from an Empanelled Jeweller, the delivery of such jewellery piece or gift voucher shall be in accordance with the delivery policies of such Empanelled Jeweller. Similarly, in the event You are not satisfied with the jewellery piece delivered to You, any exchange or refund will also be subject to the policies of the Empanelled Jewellers and Suvarnasiddhi is not responsible or liable for the actions of the Empanelled Jeweller at any point including delivery, workmanship or quality. You further agree and acknowledge that, once Your Exchange Request is processed by Suvarnasiddhi and communicated to the Empanelled Jeweller, You cannot claim refund or return of Your Customer Gold for which such Exchange Request was placed with the Empanelled Jeweller
                                        </li>
                                        <li> Upon the Empanelled Jeweller confirming Your Exchange Request, the Customer Gold Account shall be finalized by debiting the Exchanged Gold Account from the Customer Gold Account. Suvarnasiddhi shall not be liable to You for any refund/replacement, under any circumstance, for any subsequent complaints with respect to such Exchange Request, deliveries and/or any failure on Your part to comply with these Terms.
                                        </li>
                                    </ul>
                                </li>
                                <li> Notwithstanding anything to the contrary contained in these Terms, Suvarnasiddhi shall be entitled to reject a Customer Request which is not in compliance with the Terms hereof, and shall intimate the reasons for the same.
                                </li>
                                <li> Based on the changes made to the Customer Gold Account (in lieu of the Customer Orders and/or Customer Requests), if You are of the opinion that the changes made thereto do not tally with the Customer Orders and/or Customer Requests placed by You, You may write to us at [care@Suvarnasiddhi.com]. Suvarnasiddhi shall accordingly take all necessary actions for taking care of any such identified discrepancies, in a form and manner to be intimated by Suvarnasiddhi to You.
                                </li>
                                <li> It is hereby clarified that the Customer Gold cannot be pledged or transferred by You to any other user, and the Customer Gold Account is non-transferable, unless specifically allowed by Suvarnasiddhi. If specifically allowed by Suvarnasiddhi the title to such Customer Gold lying in the vault and the Customer Gold Account shall transfer to Your legal heirs only after the required due diligence has been conducted. Subsequent to this, Your legal heir(s) shall be regarded as the Customer for the purpose of the Customer Gold and Customer Gold Account thereafter and the Terms shall be applicable to Your legal heir(s).
                                </li>
                                <li> Suvarnasiddhi shall facilitate the consummation of the Customer Order(s) and/or Customer Request(s) using the Website and the Services or through a Distributor using the Platform. It is however clarified that all such purchase and fulfilment transactions are final and non-reversible, unless otherwise indicated in these Terms.
                                </li>
                                <li> It is hereby clarified that the Website displays the articles that are available for shopping. Some items may appear slightly larger or smaller than actual size due to screen defaults and photography techniques. Suvarnasiddhi shall not be liable for any legal action on this account. It shall be the endeavour of Suvarnasiddhi to ensure that all details regarding the product are clearly displayed on the Platform.
                                </li>
                                <li> Due to reasons not directly attributable to Suvarnasiddhi, data may be inaccurately displayed on the Platform due to system errors or where any part of the Platform is operated by any Distributor, then either due to system error in such part of the Platform and/or due to such Distributor making or committing any error in accurately displaying any data provided by Suvarnasiddhi. Suvarnasiddhi reserves the right to correct any and all errors when they do occur, at its sole direction, and Suvarnasiddhi shall be entitled to not honour any requests/orders placed by You based on any inaccurate or erroneous prices.
                                </li>
                                <li> The prices quoted on the Platform are fixed and not negotiable. The prices on the Platform are also subject to change without notice to You.
                                </li>
                            </ul>
                        </li>
                        <!-- 7th -->
                        <li>
                            <h4>FEES</h4>
                            <ul>
                                <li> You hereby agree that You shall be liable for all fees and charges associated with the use of the Platform and Services. Further details of the fees payable (including, but not limited to the terms pertaining to such fees and the quantum thereof), has been set out in the Section on the Platform entitled ‘Pricing and Fees’. Please note that the fees and charges may be revised from time to time and it would be Your responsibility to view the Platform to check the then current fees and charges payable.
                                </li>
                                <li> It is hereby clarified that fees and charges, once paid, are non-refundable</li>
                                <li>All payments made for the use of the Platform and/or purchase of Customer Gold by You shall be compulsorily in Indian Rupees.
                                </li>
                                <li>While availing any of the payment method/s available on the Platform for availing the Services, Suvarnasiddhi shall not be responsible for or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:
                                    <ul>
                                        <li>Lack of authorization for any transaction(s), or</li>
                                        <li>Exceeding the preset limit mutually agreed by You and between bank/s and/or other institutions used by you (including any Distributor) in making payment, or
                                        </li>
                                        <li> Any payment issues arising out of the transaction, or</li>
                                        <li> Rejection of transaction for any other reason(s) whatsoever</li>
                                    </ul>
                                </li>
                                <li> Suvarnasiddhi holds the authority to temporarily/permanently suspend/terminate the Customer Account or refuse access in case of non-payment of fees due by You to Suvarnasiddhi. Without limitation to the other rights and remedies available to Suvarnasiddhi, it also reserves the right to take legal action for the same.
                                </li>
                            </ul>
                        </li>
                        <!-- 8th -->
                        <li>
                            <h4>NATURE OF SERVICES</h4>
                            <p> You understand and acknowledge that the Services are being provided and made available on an “AS IS” and “AS AVAILABLE” basis. The Website and/or any other part of the Platform may contain errors or inaccuracies that could cause failures, corruption or loss of data and/or information from Your device and from peripherals (including, without limitation, servers and computers) connected thereto. You assume all risks and costs associated with Your use of the Services, including without limitation, any costs incurred for the use of Your device and any damage to any equipment, software or data.  </p>
                        </li>
                        <!-- 9th -->
                        <li>
                            <h4>AGREEMENT TO RECEIVE COMMUNICATION</h4>
                            <p> You hereby by way of accepting these Terms consent to the receipt of communication and newsletters from Suvarnasiddhi by way of e-mails and/or SMS notifications. You are required to intimate Suvarnasiddhi immediately of any changes to Your e-mail or mobile phone numbers. By accepting these Terms, You further authorize Suvarnasiddhi to get in touch with You for communication and promotions, despite any Do Not Disturb requests made by You. </p>
                        </li>
                        <!-- 10th -->
                        <li>
                            <h4>FEEDBACK</h4>
                            <ul>
                                <li> The Platform may allow You to post Your review and experience of using the Platform ("Reviews") in order to improve the Platform and the user experience.
                                </li>
                                <li>You, being the originator of the Reviews, are responsible for the Reviews that You upload, post, publish, transmit or otherwise makes available on the Platform. You represent that all such Reviews will be in accordance with applicable law. You acknowledge that Suvarnasiddhi does not endorse any Reviews on the Platform and is not responsible or liable for any Reviews. Suvarnasiddhi reserves the right to disable access to the Reviews on the Website or require the applicable Distributors to disable access on any part of the Platform.
                                </li>
                                <li> You hereby grant Suvarnasiddhi a perpetual, non-revocable, worldwide, royalty-free and sub-licensable right and license to use, copy, distribute, display, publish, transmit, make available, reproduce, modify, adapt the Reviews in any manner as deemed appropriate by Suvarnasiddhi in any form including but not limited to print, broadcast, online and across any and all websites and platforms owned by Suvarnasiddhi.
                                </li>
                                <li> You further represent and warrant that while posting any Reviews on any part of the Platform You shall not use any offensive, libellous, derogatory, hateful or racially or ethnically objectionable language. Further, You shall not post any content on any part of the Platform that is obscene, pornographic, constitutes an “indecent representation of women” as provided in the Indecent Representation of Women (Prohibition) Act, 1986.
                                </li>
                            </ul>
                        </li>
                        <!-- 11th -->
                        <li>
                            <h4>CONFIDENTIALITY</h4>
                            <p>As elaborated under the Privacy Policy, Suvarnasiddhi will keep all confidential information confidential, including Your personal information, and shall not disclose it to anyone except as required by law, and shall ensure that such confidential information is protected with security measures and a degree of care that it would apply to its own confidential information. Suvarnasiddhi acknowledges that its employees, directors, agents and contractors shall use the confidential information only for the intended purpose for which it is provided. Suvarnasiddhi shall use all reasonable endeavours to ensure that its employees, directors, agents and contractors acknowledge and comply with the provisions of these Terms of confidentiality as if such person was subject to these Terms of confidentiality. </p>
                        </li>
                        <!-- 12th -->
                        <li>
                            <h4>LINKS TO THIRD-PARTIES' WEBSITES</h4>
                            <p> The Website or any other part of the Platform may contain links and interactive functionality interacting with the websites of third parties. Suvarnasiddhi is not responsible for and has no liability for the functionality, actions, inactions, privacy settings, privacy policies, terms, or content of any such website. Before enabling any sharing functions to communicate with any such website or otherwise visiting any such website, Suvarnasiddhi strongly recommends that You review and understand the terms and conditions, privacy policies, settings, and information-sharing functions of each such third-party website. Further where You are using either (i) any internet website(s) operated by Distributors to avail of any Services; and/or (ii) any mobile based software applications/programs offered by any Distributor to avail of any Services; then Suvarnasiddhi is not responsible for and has no liability for the functionality, actions, inactions, privacy settings, privacy policies, terms, or content of any such website and/or mobile based software applications/programs (as may be applicable) and/or any liability whatsoever in relation to Your use of such website and/or mobile based software applications/programs (as may be applicable) save and except to the extent expressly set out in these Terms. Before enabling any sharing functions to communicate with any such website or otherwise visiting any such any such website and/or mobile based software applications/programs (as may be applicable), Suvarnasiddhi strongly recommends that You review and understand the terms and conditions, privacy policies, settings, and information-sharing functions of such any such website and/or mobile based software applications/programs (as may be applicable). </p>
                        </li>
                        <!-- 13th -->
                        <li>
                            <h4>INDEMNIFICATION</h4>
                            <p> You shall indemnify and hold harmless Suvarnasiddhi, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of these Terms, Privacy Policy and other policies, or Your violation of any law, rules or regulations or the rights (including infringement of any intellectual property rights) of a third party. </p>
                        </li>
                        <!-- 14th -->
                        <li>
                            <h4>TERMINATION</h4>
                            <ul>
                                <li> Suvarnasiddhi, in its sole discretion, may modify, suspend, or terminate access to, all or any portion of the Website and/or may require the applicable Distributor to modify, suspend, or terminate access to, all or any portion of the Platform or Your ability to access any Services through the Platform at any time for any reason including termination for breach of any of these Terms or occurrence of a Customer EoD or the Privacy Policy. The term “Customer EoD” shall mean any default by a Customer of its obligations owed to the Security Trustee, under the Security Trustee Agreements provided that for the purposes of enforcing the hypothecation created by You in favour of the Security Trustee, the Security Trustee would be required to first obtain a suitable order / direction passed in its favour from a competent judicial or statutory authority having jurisdiction in the matter.
                                </li>
                                <li>You shall be entitled to terminate the Customer Account by contacting Suvarnasiddhi at [support@suvarnasiddhi.com].
                                </li>
                                <li> These Terms shall further stand terminated:
                                    <ul>
                                        <li> if Suvarnasiddhi is adjudged bankrupt or declared insolvent;</li>
                                        <li> if Suvarnasiddhi ceases to carry on its business or has communicated to the
                                            Security Trustee any intention to cease to carry on its business;
                                        </li>
                                        <li> if Suvarnasiddhi breaches any of the terms and conditions under the Security
                                            Trustee Agreements or Terms and Suvarnasiddhi does not remedy such breach
                                            within 60 (Sixty) days of being called upon to do so by the Security
                                            Trustee;
                                        </li>
                                        <li> upon any corporate action (excluding any third party corporate action), legal proceedings or other procedures or steps being taken in relation to the suspension of payments, winding up, dissolution, administration, provisional supervision or reorganization or restructuring (by way of voluntary arrangement, scheme of arrangement or otherwise) of Suvarnasiddhi;
                                        </li>
                                        <li> upon Suvarnasiddhi commencing a voluntary proceeding under any applicable bankruptcy, insolvency, winding up or other similar applicable law now or hereafter in effect, or consenting to the entry of an order for relief in an involuntary proceeding under any such applicable law, or consenting to the appointment or taking possession by a receiver, liquidator, assignee (or similar official) for the whole or a substantial part of its property or takes any action towards its re-organization, liquidation or dissolution;
                                        </li>
                                        <li> upon an order being made for the winding up, bankruptcy or dissolution of Suvarnasiddhi, or an application is admitted for initiating any corporate insolvency resolution process against Suvarnasiddhi in accordance with Applicable Law;
                                        </li>
                                        <li> upon any encumbrancer lawfully taking possession, or a liquidator, judicial custodian, receiver, administrative receiver or trustee or any analogous officer having been appointed in respect of the whole or a substantial part of the property of Suvarnasiddhi, or an attachment, sequestration, distress or execution (or analogous process) being levied or enforced upon or issued against whole or a substantial part of the assets or property of Suvarnasiddhi, or any action has been taken or suffered against Suvarnasiddhi towards liquidation or dissolution or similar reorganization; or
                                        </li>
                                        <li> upon a liquidator or provisional liquidator being appointed to Suvarnasiddhi or a receiver, receiver and manager, trustee or similar official being appointed in respect of Suvarnasiddhi or any of its assets, or an event analogous.
                                        </li>
                                    </ul>
                                </li>
                                <li> Upon the happening of any of the events referred to in Section 14.3, and where there is any insufficiency of Suvarnasiddhi funds required to pay any costs and expenses to be incurred in relation to providing delivery of Your Customer Gold to You, then in such an event You do hereby authorise the Security Trustee to sell any part of the Customer Gold, that is necessary or required to defray such costs and expenses.
                                </li>
                                <li> Pursuant to the Security Trustee Agreements Suvarnasiddhi has created a charge by way of hypothecation in favour of the Security Trustee for the benefit of the Customers over: (a) the monies lying in the Collection Account from time to time; and (b) gold purchased by Suvarnasiddhi from time to time and lying with the Vault Keeper or in transit and, which is the property of Suvarnasiddhi; (collectively “Security”). Upon the occurrence of any of the events detailed in Section 14.1, the Security Trustee under the Security Trustee Agreements is to: (i) declare all outstanding amounts as due and payable to the Security Trustee forthwith; and (ii) take charge and/or possession of, seize, recover, receive and remove the Security and use the same to discharge any liability of Suvarnasiddhi to the Customers. You however expressly understand and acknowledge that any enforcement of the Security would always be subject to and undertaken in accordance with the provisions of Applicable Law and therefore:
                                    <ul>
                                        <li> it is not possible to accurately predict the time required to make any such distribution; and/or
                                        </li>
                                        <li>the amount received by You from such distribution may not be sufficient to completely extinguish Suvarnasiddhi’s liability to You;
                                        </li>
                                    </ul>
                                   and consequently, no liability shall accrue to the Security Trustee in relation to the above.
                                </li>
                            </ul>
                        </li>
                        <!-- 15th -->
                        <li>
                            <h4>CONSEQUENCES OF TERMINATION</h4>
                            <ul>
                                <li> Upon such termination for any reason whatsoever, subject to these Terms read with the Security Trustee Agreements:
                                    <ul>
                                        <li>Fractional amounts for gold holdings of less than 1 (One) gram may be sold and cash in pursuance thereto will be sent directly to Your bank account, after deducting all the requisite charges relating to appointment of Intermediaries (including but not limited to charges due and payable to Intermediaries and any other out of pocket expenses, custody charges, minting and delivery charges) (“Charges”).
                                        </li>
                                        <li> For larger gold holdings, the Security Trustee shall (to the extent You have not already paid for all the Charges) be allowed to sell part of Your gold to pay for all the Charges to all the Intermediaries. The remaining portion of the gold shall be delivered to You in accordance with these Terms, along with the details of the deductions made and the quantum of gold that You are entitled to receive.
                                        </li>
                                    </ul>
                                </li>
                                <li> You acknowledge that the termination of Your access to the Website and Services may be affected without any prior notice, and Suvarnasiddhi may immediately deactivate or delete the Customer Account and all related information and/or bar any further access to the Customer Account, the Website or the Services. Further, You agree that Suvarnasiddhi shall not be liable for any discontinuation or termination of Services by any third party
                                </li>
                                <li> None of Your content shall remain accessible on the Website upon termination. This information cannot be recovered by You, once the account is terminated.
                                </li>
                                <li>The disclaimer of warranties, the limitation of liability, and the governing law provisions shall survive any termination of these Terms.
                                </li>
                            </ul>
                        </li>
                        <!-- 16th -->
                        <li>
                            <h4>DISCLAIMER OF WARRANTIES</h4>
                            <p> THE WEBSITE AND ALL INFORMATION, CONTENT, MATERIALS AND SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE PLATFORM (COLLECTIVELY, THE "CONTENTS") ARE PROVIDED BY Suvarnasiddhi ON AN "AS IS," "AS AVAILABLE" BASIS, WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND. Suvarnasiddhi MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE PLATFORM, THE ACCURACY OR COMPLETENESS OF THE CONTENTS AND THE ACCURACY OF THE INFORMATION. Suvarnasiddhi SHALL HAVE NO RESPONSIBILITY FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY CONTENT, MATERIALS, DOCUMENT OR INFORMATION OR ANY OTHER LOSSES INCURRED BY YOU FOR USE OF THE WEBSITE. YOU EXPRESSLY AGREE THAT THE USE OF THE PLATFORM IS AT YOUR SOLE RISK. Suvarnasiddhi WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THE PLATFORM OR THE SERVICES OR THE CONTENTS INCLUDING, WITHOUT LIMITATION, DIRECT, INDIRECT, CONSEQUENTIAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES, UNLESS OTHERWISE SPECIFIED IN WRITING. TO THE FULL EXTENT PERMITTED BY LAW, Suvarnasiddhi DISCLAIMS ANY AND ALL REPRESENTATIONS AND WARRANTIES WITH RESPECT TO THE PLATFORM (OR ANY PART THEREOF) AND ITS CONTENTS, WHETHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE OR USE. </p>
                        </li>
                        <!-- 17th -->
                        <li>
                            <h4>LIMITATION OF LIABILITY</h4>
                            <p> You hereby acknowledge that Suvarnasiddhi (including but not limited to its, directors, employees, agents or partners) shall not be held liable to You for any special, consequential, incidental, and exemplary or punitive damages, or loss of profit or revenues. Suvarnasiddhi shall also not be liable under any circumstances for damages arising out or related in any way to Your inability to access, or Your difficulty in accessing the Platform (including through any internet website(s) operated by any Distributor to avail of any Services and/or through any mobile based software applications/programs offered by any Distributor to avail of any Services) any bugs, viruses, trojan horses, or the like, which may be transmitted to or through the Platform by any third party, any loss of Your data, any claim relating to Your data or content from the Services, Your failure to keep the Customer Account Information secure and confidential. You further agree that Suvarnasiddhi shall not be held responsible in any manner whatsoever for any and all acts of the Distributors or other Intermediaries. </p>
                        </li>
                        <!-- 18th -->
                        <li>
                            <h4>CONTENT AND INTELLECTUAL PROPERTY RIGHTS</h4>
                            <ul>
                                <li> Suvarnasiddhi solely and exclusively owns copyrights, trademarks, service marks, logos, trade names, and other intellectual and proprietary rights associated with the Services and content on the Website as well as any content provided by Suvarnasiddhi to any Distributor and displayed on/accessed via (i) any internet website(s) operated by such Distributor to avail of any Services; and/or (ii) any mobile based software applications/programs offered by such Distributor to avail of any Services. and is protected under Indian law.
                                </li>
                                <li> You hereby acknowledge that the Services constitute original works and have been developed, compiled, prepared, revised, selected, and arranged by Suvarnasiddhi through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and constitutes valuable intellectual property of Suvarnasiddhi and such others. You thereby agree to protect the proprietary rights of Suvarnasiddhi during and after the term of these Terms. You may not selectively download portions of the Platform without retaining the copyright notices. You may download material from the Platform only for the purpose intended by these Terms.
                                </li>
                                <li> Any infringement shall lead to appropriate legal proceedings against You at appropriate forum for seeking all available remedies under applicable laws of the country.
                                </li>
                            </ul>
                        </li>
                        <!-- 19th -->
                        <li>
                            <h4>GOVERNING LAW AND DISPUTE RESOLUTION</h4>
                            <p> These Terms shall be governed by and interpreted and construed in accordance with the laws of India. The courts of Mumbai shall have exclusive jurisdiction over any disputes arising under these Terms. In the event of any dispute arising out of these Terms the same shall be settled by a binding arbitration conducted by a sole arbitrator, appointed jointly by both parties and governed by the Arbitration and Conciliation Act, 1996. The venue of arbitration shall be Mumbai, Maharashtra, India.  </p>
                        </li>
                        <!-- 20th -->
                        <li>
                            <h4>ASSIGNMENT</h4>
                            <p> It is expressly agreed by the parties that Suvarnasiddhi may assign all or part of its rights or duties under these Terms without such assignment being considered a change to these Terms and without notice to You, except to the extent provided by law. </p>
                        </li>
                        <!-- 21st -->
                        <li>
                            <h4>GRIEVANCE REDRESSAL MECHANISM</h4>
                            <p> In accordance with the Information Technology Act, 2000 and Rules made thereunder, the
                                name and contact details of the Grievance Officer are provided below: </p>
                            <p> Name: Rukhsar Khan <br>
                                Address: 1902B Peninsula Business Park, G.K. Marg, Lower Parel, Mumbai 400013 <br>
                                Phone: 9920800900 <br>
                                E-mail: <a href="mailto:care@safegold.in">care@safegold.in</a></p>
                            <p> If You wish to make a complaint regarding any violation of the provisions of these
                                Terms, You
                                may send a written complaint to the Grievance Officer, who shall redress the complaint
                                in
                                accordance with the provisions of the Information Technology Act, 2000 and Rules made
                                thereunder. </p>
                        </li>
                        <!-- 22nd -->
                        <li>
                            <h4>HOW TO CONTACT US</h4>
                            <p> If You have any questions or concerns about these Terms, please contact Suvarnasiddhi at [support@suvarnasiddhi.com]. </p>
                        </li>
                        <!-- 23rd -->
                        <li>
                            <h4>AMENDMENT OF TERMS</h4>
                            <p>Please note that these Terms may be amended from time to time by Suvarnasiddhi as follows. In the event that any change/ amendment is to be made to the Terms and which is not adverse or detrimental to the You, then You would be provided 7 days’ prior notice to such changes/ amendments. In the event, any proposed changes or amendments to the Terms are adverse to or in any way detrimental to the You, then Suvarnasiddhi shall provide You with 14 days’ prior notice requiring You to opt out of the agreement/understanding on which Suvarnasiddhi would provide the Services to You as recorded in these Terms. In the event that You do not respond to any such proposed change/amendment stating that You do not accept such change/amendment and wish to opt out of the Terms, then You would be deemed to have consented to such proposed change or amendment to these Terms. </p>
                        </li>

                        <li>
                            <h4>PRICING AND FEES</h4>
                            <p>Secure storage of gold is free for the first two years. After that, we may levy a charge of up to .03% per month of the customer’s gold balance at the end of each month till the maximum storage period of 7 years is completed. Thereafter a customer will have to sell their gold or take delivery    .</p>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>